Repository TeamBeMe/BeMeAndroid, pull requests merged in 2020-12, with the labels that each got.

#7 #1 [CHORE] : Add ktlint git-precommit-hook
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  build.gradle
Labels: chore, pull request

#8 #2 [CHORE] : Add fragments and packaging
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: chore, pull request

#10 #9 [CHORE] : Add vector assets for bottom nav
  app/src/main/res/drawable/ic_explore_selected.xml
  app/src/main/res/drawable/ic_explore_unselected.xml
  app/src/main/res/drawable/ic_following_selected.xml
  app/src/main/res/drawable/ic_following_unselected.xml
  app/src/main/res/drawable/ic_home_selected.xml
  app/src/main/res/drawable/ic_home_unselected.xml
  app/src/main/res/drawable/ic_mypage_unselected.xml
Labels: chore, pull request

#11 #3 [STYLE] : Add ViewPager Bottom Nav at MainActivity
  app/src/main/res/drawable/explore_selector.xml
  app/src/main/res/drawable/following_selector.xml
  app/src/main/res/drawable/home_selector.xml
  app/src/main/res/drawable/mypage_selector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: pull request, style

#12 #5 [FEAT] : Make Adapter for Bottom Nav/ViewPager2
  app/build.gradle
  app/src/main/java/com/teambeme/beme/main/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: feat, pull request

#14 #13 [FIX] : Fix size of bottom nav icon/Add icon mypage selected
  app/src/main/res/drawable/ic_mypage_selected.xml
  app/src/main/res/drawable/mypage_selector.xml
  app/src/main/res/layout/activity_main.xml
Labels: fix, pull request

#15 Merge l2hyunwoo to Develop
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/MainActivity.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/main/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/res/drawable/explore_selector.xml
  app/src/main/res/drawable/following_selector.xml
  app/src/main/res/drawable/home_selector.xml
  app/src/main/res/drawable/ic_explore_selected.xml
  app/src/main/res/drawable/ic_explore_unselected.xml
  app/src/main/res/drawable/ic_following_selected.xml
  app/src/main/res/drawable/ic_following_unselected.xml
  app/src/main/res/drawable/ic_home_selected.xml
  app/src/main/res/drawable/ic_home_unselected.xml
  app/src/main/res/drawable/ic_mypage_selected.xml
  app/src/main/res/drawable/ic_mypage_unselected.xml
  app/src/main/res/drawable/mypage_selector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: chore, pull request

#16 #4 [FEAT] : Make BindingActivity
  app/src/main/java/com/teambeme/beme/base/BindingActivity.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
Labels: feat, pull request

#17 Merge l2hyunwoo to Develop
  app/src/main/java/com/teambeme/beme/base/BindingActivity.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
Labels: chore, pull request

#28 #27 [STYLE] : Add HomeFragment colors
  app/build.gradle
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
  app/src/main/res/values/colors.xml
Labels: l2hyunwoo, pull request, style

#30 #18 [STYLE] : Add ViewPager2 Color in HomeFragment
  app/src/main/res/layout/fragment_home.xml
Labels: l2hyunwoo, pull request, style

#37 #33 [STYLE] : Make RecyclerView otherminds from Explore
  app/src/main/res/drawable/explore_otherminds_content_shape.xml
  app/src/main/res/drawable/explore_otherminds_title_shape.xml
  app/src/main/res/drawable/ic_showdetail.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/list_explore_otherminds.xml
Labels: pull request, style, yjooooo

#41 #38 [FEAT] : Make Adapter for othermindsRecyclerView
  app/src/main/java/com/teambeme/beme/explore/adapter/OthermindsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/model/OthermindsData.kt
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/list_explore_otherminds.xml
Labels: feat, yjooooo

#45 #36 [FEAT] : Make Adapter base setting
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyChildAdapter.kt
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyChildDiffCallback.kt
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyDiffUtillCallback.kt
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyParentAdapter.kt
  app/src/main/java/com/teambeme/beme/reply/model/ReplyData.kt
  app/src/main/java/com/teambeme/beme/reply/model/ReplyParentData.kt
  app/src/main/java/com/teambeme/beme/reply/view/ReplyActivity.kt
  app/src/main/res/layout/reply_parent.xml
Labels: feat, ub1n

#46 #31 [STYLE] : Question Fragment design
  app/src/main/java/com/teambeme/beme/home/view/QuestionFragment.kt
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/question_shape_background.xml
  app/src/main/res/layout/fragment_question.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: l2hyunwoo, pull request, style

#48 #47 [FEAT] : Make QuestionPagerAdapter
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/model/Question.kt
  app/src/main/java/com/teambeme/beme/home/view/QuestionFragment.kt
  app/src/main/res/layout/item_home_question.xml
  app/src/main/res/values/styles.xml
Labels: feat, l2hyunwoo, pull request

#51 #49 [FEAT] : Connect viewpager and adapter
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
Labels: feat, l2hyunwoo, pull request

#56 #52 [FEAT] : Add ViewModel, set data function
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/util/NestedScrollableHost.kt
  app/src/main/res/layout/fragment_home.xml
Labels: feat, l2hyunwoo, pull request

#57 #42 [STYLE] : Make RecyclerView otherquestions from Explore
  app/build.gradle
  app/src/main/res/drawable-v24/img_profile_sample.png
  app/src/main/res/drawable/explore_otherquestions_shape.xml
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_reply.xml
  app/src/main/res/drawable/ic_showdetail_black.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/list_explore_otherminds.xml
  app/src/main/res/layout/list_explore_otherquestions.xml
Labels: style, yjooooo

#58 #55 [FEAT] : PageTransformer for ViewPager
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/util/ZoomOutPageTransformer.kt
Labels: feat, l2hyunwoo, pull request

#60 #43 [FEAT] : Make Adapter for otherquestions RecyclerView
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherquestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/model/OtherquestionsData.kt
  app/src/main/res/layout/list_explore_otherminds.xml
  app/src/main/res/layout/list_explore_otherquestions.xml
Labels: feat, yjooooo

#64 #40 [FEAT] : Request code review about Reply LiveData
  app/build.gradle
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyChildAdapter.kt
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyParentAdapter.kt
  app/src/main/java/com/teambeme/beme/reply/view/ReplyActivity.kt
  app/src/main/java/com/teambeme/beme/reply/viewmodel/ReplyViewModel.kt
  app/src/main/res/layout/activity_reply.xml
  app/src/main/res/layout/reply_child.xml
  app/src/main/res/layout/reply_parent.xml
Labels: feat, ub1n

#66 #62 [FEAT] : Make BindingAdapter, DummyData for otherminds RecyclerView
  app/build.gradle
  app/src/main/java/com/teambeme/beme/explore/ExploreBinding.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/list_explore_otherminds.xml
Labels: feat, yjooooo

#67 [FEAT] : Make BindingAdapter, DummyData for otherquestinos RecyclerView
  app/src/main/java/com/teambeme/beme/explore/ExploreBinding.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/list_explore_otherquestions.xml
Labels: feat, pull request, yjooooo
