Repository TeamBeMe/BeMeAndroid, pull requests merged in 2021-04, with the labels that each got.

#642 Merge release to devleop
  .github/workflows/build.yml
  .idea/sonarIssues.xml
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/signup/view/PermissionInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/SignUpActivity.kt
Labels: l2hyunwoo, pull request

#644 질문 수정 1일 1회 제한 기능 구현
  .idea/sonarIssues.xml
  README.md
  app/build.gradle
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/data/local/singleton/BeMeRepository.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/teambeme/beme/onboarding/view/OnBoardingActivity.kt
  app/src/main/java/com/teambeme/beme/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/teambeme/beme/setting/view/SettingActivity.kt
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
  app/src/main/java/com/teambeme/beme/util/AuthInterceptor.kt
  build.gradle
Labels: l2hyunwoo, pull request

#648 UI 고쳐야할 부분 고침
  .idea/sonarIssues.xml
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/res/layout/activity_answer.xml
Labels: l2hyunwoo, pull request

#650 #649 [STYLE] Answer : 답안 UI 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_answer.xml
Labels: pull request, yjooooo

#651 Instant Search 구현
  .idea/sonarIssues.xml
  app/build.gradle
  app/src/main/java/com/teambeme/beme/data/remote/api/IdSearchService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/IdSearchDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/IdSearchDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/repository/IdSearchRepository.kt
  app/src/main/java/com/teambeme/beme/data/repository/IdSearchRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/RecentSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
  app/src/main/res/layout/activity_following_after_id_search.xml
Labels: l2hyunwoo, pull request

#654 #652 [FIX] : 키보드 올라와도 스크롤 가능하게 UI 개선
  app/src/main/res/layout/activity_answer.xml
Labels: l2hyunwoo, pull request

#655 #653 [FIX] : 오늘 질문 적었으면 새로운 질문 받을 수 있게
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
Labels: fix, l2hyunwoo, pull request

#658 [FEAT] 키보드 관련 이슈 해결
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/res/layout/activity_answer.xml
Labels: pull request, yjooooo

#659 Release 1.1.2
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/res/layout/activity_answer.xml
Labels: pull request

#660 Release/1.1.2
  .idea/sonarIssues.xml
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/data/local/singleton/BeMeRepository.kt
  app/src/main/java/com/teambeme/beme/data/remote/api/IdSearchService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/IdSearchDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/IdSearchDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/repository/IdSearchRepository.kt
  app/src/main/java/com/teambeme/beme/data/repository/IdSearchRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/RecentSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/teambeme/beme/onboarding/view/OnBoardingActivity.kt
  app/src/main/java/com/teambeme/beme/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/teambeme/beme/setting/view/SettingActivity.kt
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
  app/src/main/java/com/teambeme/beme/util/AuthInterceptor.kt
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_following_after_id_search.xml
  build.gradle
Labels: pull request

#665 MyPage 관련 이슈들 해결
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/mypage/model/CategoryFilter.kt
  app/src/main/java/com/teambeme/beme/mypage/model/PublicRange.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomWriteFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
Labels: pull request, yjooooo
