Repository TeamBeMe/BeMeAndroid, pull requests merged in 2021-02, with the labels that each got.

#501 Fix Bug in Explore
  app/src/main/res/layout/activity_explore_detail.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
Labels: pull request, yjooooo

#502 Fix Bug in Explore
  app/src/main/res/layout/activity_explore_detail.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
Labels: pull request

#504 #503 [FEAT] : 자동로그인 구현
  app/build.gradle
  app/src/main/java/com/teambeme/beme/data/remote/singleton/BeMeAuthPreference.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
Labels: feat, l2hyunwoo, pull request

#507 [FIX] : Home, 글쓰기 부분 에러 해결
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
Labels: fix, l2hyunwoo, pull request

#508 Release to develop
  app/build.gradle
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/BeMeAuthPreference.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
Labels: pull request

#511 #510 [CHORE] : Gradle 버전넘버 버전네임 설정
  .gitignore
  app/build.gradle
  build.gradle
Labels: chore, l2hyunwoo, pull request

#520 Ub1n
  app/src/main/java/com/teambeme/beme/otherpage/adapter/OtherPageAdapter.kt
Labels: fix, pull request, ub1n

#526 Yjooooo
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/item_explore_detail_other_answers.xml
  app/src/main/res/values/styles.xml
Labels: pull request, yjooooo

#532 Fix Bug
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreDetailActivity.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/res/layout/activity_answer.xml
Labels: pull request, yjooooo

#534 Fix Answer Card Design at FollowingFragment.
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/drawable/switch_thumb.xml
  app/src/main/res/layout/item_explore_other_questions.xml
Labels: pull request, yjooooo

#538 Merge l2hyunwoo to develop
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/base/BindingFragment.kt
  app/src/main/java/com/teambeme/beme/data/local/singleton/BeMeAuthPreference.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/teambeme/beme/onboarding/adapter/OnBoardingAdapter.kt
  app/src/main/java/com/teambeme/beme/onboarding/model/OnBoardingData.kt
  app/src/main/java/com/teambeme/beme/onboarding/view/OnBoardingActivity.kt
  app/src/main/java/com/teambeme/beme/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/teambeme/beme/onboarding/viewmodel/OnBoardingViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/setting/view/SettingActivity.kt
  app/src/main/java/com/teambeme/beme/signup/view/OnBoardFragment.kt
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
  app/src/main/java/com/teambeme/beme/util/AuthInterceptor.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_onboarding_01.xml
  app/src/main/res/drawable/ic_onboarding_02.xml
  app/src/main/res/drawable/ic_onboarding_03.xml
  app/src/main/res/drawable/ic_onboarding_04.xml
  app/src/main/res/drawable/onboarding_button_background.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/fragment_on_board.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/values/colors.xml
Labels: feat, l2hyunwoo, pull request

#541 Update Version
  .gitignore
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/base/BindingFragment.kt
  app/src/main/java/com/teambeme/beme/data/local/singleton/BeMeAuthPreference.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreDetailActivity.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/teambeme/beme/onboarding/adapter/OnBoardingAdapter.kt
  app/src/main/java/com/teambeme/beme/onboarding/model/OnBoardingData.kt
  app/src/main/java/com/teambeme/beme/onboarding/view/OnBoardingActivity.kt
  app/src/main/java/com/teambeme/beme/onboarding/viewmodel/OnBoardingViewModel.kt
  app/src/main/java/com/teambeme/beme/onboarding/viewmodel/OnBoardingViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/otherpage/adapter/OtherPageAdapter.kt
  app/src/main/java/com/teambeme/beme/setting/view/SettingActivity.kt
  app/src/main/java/com/teambeme/beme/signup/view/OnBoardFragment.kt
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
  app/src/main/java/com/teambeme/beme/util/AuthInterceptor.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_onboarding_01.xml
  app/src/main/res/drawable/ic_onboarding_02.xml
  app/src/main/res/drawable/ic_onboarding_03.xml
  app/src/main/res/drawable/ic_onboarding_04.xml
  app/src/main/res/drawable/onboarding_button_background.xml
  app/src/main/res/drawable/switch_thumb.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/fragment_on_board.xml
  app/src/main/res/layout/item_explore_detail_other_answers.xml
  app/src/main/res/layout/item_explore_other_questions.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: pull request

#542 #539 [FEAT] : 오픈소스 라이센스 달았다
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/setting/adapter/OpenSourceAdapter.kt
  app/src/main/java/com/teambeme/beme/setting/model/OpenSourceData.kt
  app/src/main/java/com/teambeme/beme/setting/view/OpenSourceActivity.kt
  app/src/main/java/com/teambeme/beme/setting/view/SettingActivity.kt
  app/src/main/res/layout/activity_open_source.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/item_opensource.xml
Labels: feat, l2hyunwoo, pull request

#546 Feature/l2hyunwoo fix home
  app/build.gradle
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/res/layout/item_home_question.xml
Labels: l2hyunwoo, pull request

#552 Merge l2hyunwoo to develop
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/di/ApiModule.kt
  app/src/main/java/com/teambeme/beme/di/RetrofitModule.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  build.gradle
  buildSrc/.gitignore
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: l2hyunwoo, pull request

#554 Merge l2hyunwoo develop
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherMindsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/main/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/main/model/ScreenName.kt
  app/src/main/java/com/teambeme/beme/mypage/model/CategoryFilter.kt
  app/src/main/java/com/teambeme/beme/mypage/model/PublicRange.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomWriteFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/java/com/teambeme/beme/notification/adapter/NoticeAdapter.kt
  app/src/main/java/com/teambeme/beme/onboarding/view/OnBoardingActivity.kt
  app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PermissionInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PersonalInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/TermFragment.kt
  app/src/main/java/com/teambeme/beme/util/FirebaseEventUtil.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_my_write.xml
Labels: l2hyunwoo, pull request
