Repository TeamBeMe/BeMeAndroid, pull requests merged in 2021-03, with the labels that each got.

#556 #555 [FIX] : 약관 텍스트로 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/fragment_term.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/values/strings.xml
Labels: fix, l2hyunwoo, pull request

#557 Release/1.0.3
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/fragment_term.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/values/strings.xml
Labels: l2hyunwoo, pull request

#558 Release/1.0.3
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/di/ApiModule.kt
  app/src/main/java/com/teambeme/beme/di/RetrofitModule.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherMindsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/main/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/main/model/ScreenName.kt
  app/src/main/java/com/teambeme/beme/mypage/model/CategoryFilter.kt
  app/src/main/java/com/teambeme/beme/mypage/model/PublicRange.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomWriteFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/java/com/teambeme/beme/notification/adapter/NoticeAdapter.kt
  app/src/main/java/com/teambeme/beme/onboarding/view/OnBoardingActivity.kt
  app/src/main/java/com/teambeme/beme/setting/adapter/OpenSourceAdapter.kt
  app/src/main/java/com/teambeme/beme/setting/model/OpenSourceData.kt
  app/src/main/java/com/teambeme/beme/setting/view/OpenSourceActivity.kt
  app/src/main/java/com/teambeme/beme/setting/view/SettingActivity.kt
  app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PermissionInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PersonalInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/TermFragment.kt
  app/src/main/java/com/teambeme/beme/util/FirebaseEventUtil.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_on_boarding.xml
  app/src/main/res/layout/activity_open_source.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_my_write.xml
  app/src/main/res/layout/fragment_term.xml
  app/src/main/res/layout/item_home_question.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/layout/item_opensource.xml
  app/src/main/res/values/strings.xml
  build.gradle
  buildSrc/.gitignore
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: l2hyunwoo, pull request

#559 #549 [DOCS] : README.md 수정
  README.md
Labels: l2hyunwoo, pull request

#576 Yjooooo
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
Labels: pull request, yjooooo

#583 Yjooooo
  app/src/main/res/drawable/tag_layout.xml
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
  app/src/main/res/layout/item_myscrap.xml
  app/src/main/res/layout/item_mywrite.xml
Labels: pull request, yjooooo

#590 Yjooooo
  app/build.gradle
  app/src/main/java/com/teambeme/beme/data/remote/api/ExploreService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/ExploreDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/ExploreDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/model/ResponseExplorationQuestions.kt
  app/src/main/java/com/teambeme/beme/explore/repository/ExploreRepository.kt
  app/src/main/java/com/teambeme/beme/explore/repository/ExploreRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
Labels: pull request, yjooooo

#596 Yjooooo
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyWriteAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/drawable/tag_layout.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
  app/src/main/res/layout/item_myscrap.xml
  app/src/main/res/layout/item_mywrite.xml
Labels: pull request, yjooooo

#599 [STYLE] : Modify Layout Margin.
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/values/colors.xml
Labels: pull request, yjooooo

#603 Yjooooo
  app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
Labels: pull request, yjooooo

#606 Refactor MyWrite, MyScrap Recyclerview Adapter.
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyScrapAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyWriteAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/item_myscrap.xml
  app/src/main/res/layout/item_mywrite.xml
Labels: refactor, yjooooo

#608 Merge update to develop
  app/build.gradle
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
Labels: l2hyunwoo, pull request

#609 Modify OtherQuestionsRcvAdapter
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
Labels: pull request, yjooooo

#615 Yjooooo
  app/src/main/java/com/teambeme/beme/otherpage/adapter/OtherPageAdapter.kt
  app/src/main/java/com/teambeme/beme/otherpage/view/OtherPageActivity.kt
  app/src/main/java/com/teambeme/beme/otherpage/viewmodel/OtherPageViewModel.kt
  app/src/main/res/layout/activity_other_page.xml
  app/src/main/res/layout/item_myscrap.xml
  app/src/main/res/layout/item_mywrite.xml
  app/src/main/res/layout/item_other_page.xml
Labels: pull request, yjooooo

#616 Yjooooo
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/otherpage/adapter/OtherPageAdapter.kt
  app/src/main/java/com/teambeme/beme/otherpage/view/OtherPageActivity.kt
  app/src/main/java/com/teambeme/beme/otherpage/viewmodel/OtherPageViewModel.kt
  app/src/main/res/layout/activity_other_page.xml
  app/src/main/res/layout/item_myscrap.xml
  app/src/main/res/layout/item_mywrite.xml
  app/src/main/res/layout/item_other_page.xml
Labels: pull request, yjooooo

#617 Merge release to develop
  .idea/sonarIssues.xml
  app/build.gradle
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
Labels: l2hyunwoo, pull request

#631 [CHORE] : gradle 의존성 update
  app/build.gradle
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  build.gradle
Labels: chore, l2hyunwoo

#637 Fix viewpager2 exception error
  .idea/sonarIssues.xml
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/main/viewmodel/EventViewModel.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomProfileFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomWriteFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/teambeme/beme/util/SingleLiveEvent.kt
  build.gradle
Labels: fix, l2hyunwoo, pull request

#628 Fix Bug And Fix Layout
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/main/adapter/MainViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/main/model/ScreenName.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyWriteAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/java/com/teambeme/beme/util/RecordScreenUtil.kt
  app/src/main/res/layout/activity_other_page.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
  app/src/main/res/menu/menu_main.xml
Labels: pull request, yjooooo

#639 Fix Bug.
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
Labels: pull request, yjooooo

#641 Hotfix register error
  .github/workflows/build.yml
  .idea/sonarIssues.xml
  app/src/main/java/com/teambeme/beme/signup/view/PermissionInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/SignUpActivity.kt
Labels: l2hyunwoo, pull request
