Repository TeamBeMe/BeMeAndroid, pull requests merged in 2021-01, with the labels that each got.

#75 #61 [STYLE] : Make Tab, Chip in Explore Fragment
  app/build.gradle
  app/src/main/res/drawable/explore_chip_shape.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: style, yjooooo

#77 suspend work
  app/build.gradle
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/util/TransparentStatusBarObject.kt
Labels: pull request

#78 Merge l2hyunwoo to develop
  app/build.gradle
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/model/Question.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/teambeme/beme/util/NestedScrollableHost.kt
  app/src/main/java/com/teambeme/beme/util/TransparentStatusBarObject.kt
  app/src/main/java/com/teambeme/beme/util/ZoomOutPageTransformer.kt
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/question_shape_background.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_question.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: chore, pull request

#83 [CHORE] : Hot fix codes and solve errors
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyScrapFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyWriteFragment.kt
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyParentAdapter.kt
  app/src/main/java/com/teambeme/beme/reply/view/ReplyActivity.kt
  app/src/main/res/layout/item_this_week_back_question.xml
Labels: chore, l2hyunwoo, pull request

#84 Merge l2hyunwoo to develop
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/layout/activity_main.xml
Labels: chore, l2hyunwoo, pull request

#89 [CHORE] : Fix codes because of ktlint
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyScrapAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyWriteAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/model/MyScrap.kt
  app/src/main/java/com/teambeme/beme/mypage/model/MyWrite.kt
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyChildAdapter.kt
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyChildDiffCallback.kt
  app/src/main/java/com/teambeme/beme/reply/adapter/ReplyDiffUtillCallback.kt
Labels: chore, l2hyunwoo, pull request

#91 l2hyunwoo: Make Util Function
  app/build.gradle
  app/src/main/java/com/teambeme/beme/main/view/MainActivity.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/java/com/teambeme/beme/util/StatusBarUtil.kt
  app/src/main/res/values/colors.xml
Labels: chore, pull request

#101 #100 [REFACTOR] : Delete BindingAdapter for otherminds RecyclerView & Make setObserver for otherminds RecyclerView
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/layout/fragment_explore.xml
Labels: refactor, yjooooo

#107 Yjooooo explore
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
Labels: fix, yjooooo

#123 Yjooooo explore
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/res/color/explore_chip_selector.xml
  app/src/main/res/color/explore_chipstroke_selector.xml
  app/src/main/res/color/explore_chiptext_selector.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/list_explore_otherminds.xml
Labels: feat, pull request, style, yjooooo

#124 Merge l2hyunwoo_answer to develop
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/data/local/dao/AnswerDao.kt
  app/src/main/java/com/teambeme/beme/data/local/database/AppDatabase.kt
  app/src/main/java/com/teambeme/beme/data/local/entity/AnswerData.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/model/Question.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/drawable/answer_switch_selector.xml
  app/src/main/res/drawable/home_answer_button.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/switch_selected_false.xml
  app/src/main/res/drawable/switch_selected_true.xml
  app/src/main/res/drawable/switch_thumb.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_question.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feat, l2hyunwoo, pull request

#140 #139 [REFACTOR] : Project refactoring
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/drawable-v24/ic_beme_logo.jpg
  app/src/main/res/drawable-v24/ic_beme_round.png
  app/src/main/res/drawable/ic_beme_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_beme_background.xml
Labels: l2hyunwoo, pull request, refactor

#144 #143 [CHORE] : Setting FireBase
  app/build.gradle
  app/google-services.json
  build.gradle
Labels: chore, l2hyunwoo, pull request

#142 Yjooooo explore
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/explore/adapter/OthermindsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherquestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/model/OthermindsData.kt
  app/src/main/java/com/teambeme/beme/explore/model/OtherquestionsData.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreDetailActivity.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/java/com/teambeme/beme/util/startActivity.kt
  app/src/main/res/color/explore_chip_selector.xml
  app/src/main/res/color/explore_chipstroke_selector.xml
  app/src/main/res/color/explore_chiptext_selector.xml
  app/src/main/res/drawable/explore_otherminds_content_shape.xml
  app/src/main/res/drawable/explore_otherminds_title_shape.xml
  app/src/main/res/drawable/explore_otherquestions_shape.xml
  app/src/main/res/drawable/ic_3dot.xml
  app/src/main/res/drawable/ic_arrow_back_black.xml
  app/src/main/res/drawable/ic_bookmark_checked.xml
  app/src/main/res/layout/activity_explore_detail.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/list_explore_otherminds.xml
  app/src/main/res/layout/list_explore_otherquestions.xml
  app/src/main/res/layout/list_exploredetail_otheranswers.xml
  app/src/main/res/values/colors.xml
Labels: feat, pull request, yjooooo

#158 [REFACTOR]
  app/src/main/res/drawable-v24/img_profile_sample.png
  app/src/main/res/drawable/img_profile_sample.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: pull request, refactor

#164 #163 [FEAT] : Delete Reply
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/detail/adapter/ReplyAdapter.kt
  app/src/main/java/com/teambeme/beme/detail/adapter/ReplyChildAdapter.kt
  app/src/main/java/com/teambeme/beme/detail/adapter/ReplyChildDiffCallback.kt
  app/src/main/java/com/teambeme/beme/detail/adapter/ReplyDiffUtillCallback.kt
  app/src/main/java/com/teambeme/beme/detail/adapter/ReplyParentAdapter.kt
  app/src/main/java/com/teambeme/beme/detail/model/ReplyParentData.kt
  app/src/main/java/com/teambeme/beme/detail/view/BottomMyOtherReplyFragment.kt
  app/src/main/java/com/teambeme/beme/detail/view/BottomMyReplyFragment.kt
  app/src/main/java/com/teambeme/beme/detail/view/BottomOtherReplyFragment.kt
  app/src/main/java/com/teambeme/beme/detail/view/DetailActivity.kt
  app/src/main/java/com/teambeme/beme/detail/viewmodel/DetailViewModel.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherMindsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/model/OtherMindsData.kt
  app/src/main/java/com/teambeme/beme/explore/model/OtherQuestionsData.kt
Labels: feat, pull request, ub1n

#174 #170 [DOCS] : Document 링크 수정
  README.md
Labels: docs, l2hyunwoo, pull request

#189 [CHORE] : 푸시 알림 구현관련 풀리퀘 문제로 다시 새 브랜치 파서 작업
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/MyFirebaseMessagingService.kt
  app/src/main/java/com/teambeme/beme/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/teambeme/beme/notification/NotificationActivity.kt
  app/src/main/java/com/teambeme/beme/notification/adapter/BackQuestionAdapter.kt
  app/src/main/res/values/strings.xml
Labels: pull request, semin

#192 Merge l2hyunwoo_docs to develop
  README.md
  app/build.gradle
  document/BaseViewController.md
  document/NestedScrollableHost.md
  document/RoomDataConnection.md
  document/StatusBarUtil.md
Labels: chore, docs, l2hyunwoo, pull request

#193 #177 [DOCS] : Readme 글 정리
  document/BaseViewController.md
  document/NestedScrollableHost.md
  document/RoomDataConnection.md
  document/StatusBarUtil.md
Labels: docs, l2hyunwoo, pull request

#196 Merge l2hyunwoo_home to Develop
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/detail/viewmodel/DetailViewModel.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/InfoChangeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomProfileFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/drawable/home_bottomsheet_background.xml
  app/src/main/res/drawable/ic_home_delete.xml
  app/src/main/res/drawable/ic_home_edit.xml
  app/src/main/res/layout/fragment_info_change.xml
  app/src/main/res/values/colors.xml
Labels: feat, l2hyunwoo, pull request

#201 [FEAT] : AnswerActivity.kt modify
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/java/com/teambeme/beme/util/DisplayUtil.kt
  app/src/main/res/layout/activity_answer.xml
Labels: feat, l2hyunwoo, pull request

#205 Yjooooo following
  app/src/main/res/values/styles.xml
Labels: refactor

#209 issue track : #206 [STYLE] : OtherPage Ui , #207 [FEAT] : Other Page …
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/detail/view/BottomOtherReplyFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyWriteAdapter.kt
  app/src/main/java/com/teambeme/beme/otherpage/adapter/OtherPageAdapter.kt
  app/src/main/java/com/teambeme/beme/otherpage/model/ResponseOtherData.kt
  app/src/main/java/com/teambeme/beme/otherpage/view/OtherPageActivity.kt
  app/src/main/java/com/teambeme/beme/otherpage/viewmodel/OtherPageViewModel.kt
  app/src/main/res/drawable/ic_arrow_back_white.xml
  app/src/main/res/drawable/ic_dot3_white.xml
  app/src/main/res/drawable/ic_scrap_off_mypage.xml
  app/src/main/res/layout/activity_other_page.xml
  app/src/main/res/layout/item_other_page.xml
Labels: feat, pull request, style, ub1n

#212 #211 [CHORE] : Add gmarket sans font
  .idea/codeStyles/Project.xml
  app/src/main/res/font/gmarket_sans.xml
  app/src/main/res/font/gmarket_sans_bold.ttf
  app/src/main/res/font/gmarket_sans_light.ttf
  app/src/main/res/font/gmarket_sans_medium.ttf
Labels: chore, l2hyunwoo, pull request

#220 Merge login to l2hyunwoo
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/data/remote/api/LoginService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/LoginDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/LoginDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/login/model/RequestLogin.kt
  app/src/main/java/com/teambeme/beme/login/model/ResponseLogin.kt
  app/src/main/java/com/teambeme/beme/login/repository/LoginRepository.kt
  app/src/main/java/com/teambeme/beme/login/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/util/EnqueueUtil.kt
  app/src/main/java/com/teambeme/beme/util/KeyboardVisibilityUtils.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feat, l2hyunwoo, pull request

#221 #216 [FIX] : Login server 연동
  app/src/main/java/com/teambeme/beme/login/repository/LoginRepository.kt
  app/src/main/java/com/teambeme/beme/login/repository/LoginRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
Labels: feat, l2hyunwoo, pull request

#223 AnswerViewModel error fixed
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
Labels: fix, l2hyunwoo, pull request

#226 Ub1n other
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/data/remote/api/OtherService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/OtherPageDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/OtherPageDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teambeme/beme/otherpage/model/ResponseOtherData.kt
  app/src/main/java/com/teambeme/beme/otherpage/repository/OtherPageRepository.kt
  app/src/main/java/com/teambeme/beme/otherpage/repository/OtherPageRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/otherpage/view/OtherPageActivity.kt
  app/src/main/java/com/teambeme/beme/otherpage/viewmodel/OtherPageViewModel.kt
  app/src/main/java/com/teambeme/beme/otherpage/viewmodel/OtherPageViewModelFactory.kt
  app/src/main/res/layout/activity_other_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
Labels: feat, style, ub1n

#269 Yjooooo following
  app/src/main/java/com/teambeme/beme/data/remote/api/ExploreService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/ExploreDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/ExploreDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherMindsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/model/OtherMindsData.kt
  app/src/main/java/com/teambeme/beme/explore/model/ResponseExplorationAnswers.kt
  app/src/main/java/com/teambeme/beme/explore/model/ResponseExplorationQuestionForFirstAnswer.kt
  app/src/main/java/com/teambeme/beme/explore/model/ResponseExplorationQuestions.kt
  app/src/main/java/com/teambeme/beme/explore/model/ResponseExplorationScrap.kt
  app/src/main/java/com/teambeme/beme/explore/repository/ExploreRepository.kt
  app/src/main/java/com/teambeme/beme/explore/repository/ExploreRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreDetailActivity.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingShowAllActivity.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/java/com/teambeme/beme/util/StartActivityUtil.kt
  app/src/main/res/layout/activity_explore_detail.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/item_explore_detail_other_answers.xml
  app/src/main/res/layout/item_explore_other_minds.xml
  app/src/main/res/layout/item_explore_other_questions.xml
  app/src/main/res/values/colors.xml
Labels: pull request, yjooooo

#271 [FIX] FIX Gramatical Error
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
Labels: fix, pull request, yjooooo

#272 Merge l2hyunwoo to Develop
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/data/remote/api/SignUpService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/SignUpDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/SignUpDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/FollowingAfterIdSearchActivity.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/notification/NotificationActivity.kt
  app/src/main/java/com/teambeme/beme/signup/model/RequestSignUp.kt
  app/src/main/java/com/teambeme/beme/signup/model/ResponseNickDoubleCheck.kt
  app/src/main/java/com/teambeme/beme/signup/model/ResponseSignUp.kt
  app/src/main/java/com/teambeme/beme/signup/repository/SignUpRepository.kt
  app/src/main/java/com/teambeme/beme/signup/repository/SignUpRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PermissionInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PersonalInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/SignUpActivity.kt
  app/src/main/java/com/teambeme/beme/signup/view/TermFragment.kt
  app/src/main/java/com/teambeme/beme/signup/viewmodel/SignUpViewModel.kt
  app/src/main/res/drawable/btn_signup_background.xml
  app/src/main/res/drawable/constraint_view_image_add.xml
  app/src/main/res/drawable/ic_image_add.xml
  app/src/main/res/drawable/ic_personal_check_blue.xml
  app/src/main/res/drawable/ic_personal_check_gray.xml
  app/src/main/res/drawable/ic_personal_check_red.xml
  app/src/main/res/drawable/image_add_crop.xml
  app/src/main/res/drawable/personal_info_edittext_background.xml
  app/src/main/res/drawable/progress_bar_drawble.xml
  app/src/main/res/drawable/signup_button_background.xml
  app/src/main/res/drawable/signup_button_disabled.xml
  app/src/main/res/drawable/signup_button_enabled.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_image_choose.xml
  app/src/main/res/layout/fragment_permission_info.xml
  app/src/main/res/layout/fragment_personal_info.xml
  app/src/main/res/layout/fragment_term.xml
  app/src/main/res/navigation/sign_up_nav.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: l2hyunwoo, pull request

#273 [DOCS] : README 수정
  README.md
Labels: docs, l2hyunwoo, pull request

#282 Merge Login Function
  app/build.gradle
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/data/remote/api/LoginService.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/BeMeAuthPreference.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/login/model/ResponseLogin.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/mypage/model/ResponseProfile.kt
  app/src/main/java/com/teambeme/beme/mypage/repository/MyPageRepository.kt
  app/src/main/java/com/teambeme/beme/mypage/repository/MyPageRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomProfileFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/teambeme/beme/otherpage/viewmodel/OtherPageViewModel.kt
  app/src/main/java/com/teambeme/beme/util/AuthInterceptor.kt
Labels: l2hyunwoo, pull request

#286 [FIX] : 로그인 뷰, 홈 뷰 원상 복구
  app/src/main/java/com/teambeme/beme/data/remote/api/LoginService.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teambeme/beme/util/ErrorBody.kt
  app/src/main/res/layout/activity_login.xml
Labels: l2hyunwoo, pull request

#296 [FEAT] Connecting Server to FollowingFragment & FollowingShowAllActivity
  app/src/main/java/com/teambeme/beme/data/remote/api/ExploreService.kt
  app/src/main/java/com/teambeme/beme/data/remote/api/FollowingService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/ExploreDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/ExploreDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/FollowingDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/FollowingDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherMindsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/model/OtherQuestionsData.kt
  app/src/main/java/com/teambeme/beme/explore/model/ResponseExplorationMinds.kt
  app/src/main/java/com/teambeme/beme/explore/repository/ExploreRepository.kt
  app/src/main/java/com/teambeme/beme/explore/repository/ExploreRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/adapter/FollowerProfilesRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/adapter/FollowingProfilesRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/adapter/SearchProfilesRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/model/ResponseFollowingList.kt
  app/src/main/java/com/teambeme/beme/following/model/ResponseFollowingSearchId.kt
  app/src/main/java/com/teambeme/beme/following/repository/FollowingRepository.kt
  app/src/main/java/com/teambeme/beme/following/repository/FollowingRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingShowAllActivity.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModelFactory.kt
  app/src/main/res/layout/activity_following_show_all.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/item_explore_detail_other_answers.xml
  app/src/main/res/layout/item_explore_other_minds.xml
  app/src/main/res/layout/item_explore_other_questions.xml
  app/src/main/res/layout/item_following_profiles_of_follower.xml
  app/src/main/res/layout/item_following_profiles_of_following.xml
  app/src/main/res/layout/item_following_show_all_profiles_of_follower.xml
  app/src/main/res/layout/item_following_show_all_profiles_of_following.xml
  app/src/main/res/layout/item_following_show_all_profiles_of_search_follower.xml
  app/src/main/res/layout/item_following_show_all_profiles_of_search_following.xml
Labels: pull request, yjooooo

#298 Merge l2hyunwoo to develop
  app/src/main/java/com/teambeme/beme/data/remote/api/HomeService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/HomeDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/HomeDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/model/Answer.kt
  app/src/main/java/com/teambeme/beme/home/model/RequestModifyPublic.kt
  app/src/main/java/com/teambeme/beme/home/model/ResponseAnswer.kt
  app/src/main/java/com/teambeme/beme/home/model/ResponseAnswers.kt
  app/src/main/java/com/teambeme/beme/home/model/ResponseModifyData.kt
  app/src/main/java/com/teambeme/beme/home/repository/HomeRepository.kt
  app/src/main/java/com/teambeme/beme/home/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/home/view/AnswerSuggestFragment.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/layout/item_home_question.xml
Labels: l2hyunwoo, pull request

#303 Merge l2hyunwoo to Develop
  app/src/main/java/com/teambeme/beme/data/remote/api/HomeService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/HomeDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/HomeDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/model/Answer.kt
  app/src/main/java/com/teambeme/beme/home/repository/HomeRepository.kt
  app/src/main/java/com/teambeme/beme/home/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/view/InfoChangeFragment.kt
  app/src/main/java/com/teambeme/beme/home/view/TransitionPublicFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_unlock.xml
  app/src/main/res/layout/item_home_question.xml
Labels: feat, l2hyunwoo, pull request

#306 #304 [FEAT] : Infinite Scroll Implementation
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
Labels: l2hyunwoo, pull request

#307 IntetnAnswerData 형식 참고하세요!
  app/src/main/java/com/teambeme/beme/answer/model/IntentAnswerData.kt
  app/src/main/java/com/teambeme/beme/data/local/entity/AnswerData.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/model/Answer.kt
Labels: l2hyunwoo, pull request

#315 Answer Room까지 구현
  app/src/main/java/com/teambeme/beme/answer/model/RequestAnswerData.kt
  app/src/main/java/com/teambeme/beme/answer/model/ResponseAnswerStatus.kt
  app/src/main/java/com/teambeme/beme/answer/repository/AnswerRepository.kt
  app/src/main/java/com/teambeme/beme/answer/repository/AnswerRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/data/local/entity/AnswerData.kt
  app/src/main/java/com/teambeme/beme/data/remote/api/AnswerService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/AnswerDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/AnswerDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModelFactory.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
  app/src/main/java/com/teambeme/beme/notification/adapter/NoticeAdapter.kt
  app/src/main/java/com/teambeme/beme/notification/view/NotificationActivity.kt
  app/src/main/res/layout/activity_answer.xml
Labels: feat, l2hyunwoo, pull request

#317 #316 [FEAT] : 글쓰기 POST 기능 구현
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/model/Answer.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
Labels: feat, l2hyunwoo

#322 Yjooooo following
  app/src/main/java/com/teambeme/beme/data/remote/api/ExploreService.kt
  app/src/main/java/com/teambeme/beme/data/remote/api/FollowingService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/ExploreDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/ExploreDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/FollowingDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/FollowingDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/explore/model/ResponseExplorationQuestions.kt
  app/src/main/java/com/teambeme/beme/explore/repository/ExploreRepository.kt
  app/src/main/java/com/teambeme/beme/explore/repository/ExploreRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreDetailActivity.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/adapter/FollowingProfilesRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/adapter/SearchProfilesRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/model/RequestFollowingFollow.kt
  app/src/main/java/com/teambeme/beme/following/model/ResponseFollowingFollow.kt
  app/src/main/java/com/teambeme/beme/following/model/ResponseFollowingSearchId.kt
  app/src/main/java/com/teambeme/beme/following/repository/FollowingRepository.kt
  app/src/main/java/com/teambeme/beme/following/repository/FollowingRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingShowAllActivity.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/res/drawable/ic_idsearch.xml
  app/src/main/res/layout/activity_following_show_all.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
  app/src/main/res/layout/item_explore_other_minds.xml
  app/src/main/res/layout/item_explore_other_questions.xml
  app/src/main/res/layout/item_following_show_all_profiles_of_following.xml
  app/src/main/res/layout/item_following_show_all_profiles_of_search_follower.xml
  app/src/main/res/layout/item_following_show_all_profiles_of_search_following.xml
Labels: feat, yjooooo

#353 회원가입 기능 구현 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/data/remote/api/SignUpService.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/SignUpDataSource.kt
  app/src/main/java/com/teambeme/beme/data/remote/datasource/SignUpDataSourceImpl.kt
  app/src/main/java/com/teambeme/beme/signup/model/RequestSignUp.kt
  app/src/main/java/com/teambeme/beme/signup/repository/SignUpRepository.kt
  app/src/main/java/com/teambeme/beme/signup/repository/SignUpRepositoryImpl.kt
  app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PersonalInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/viewmodel/SignUpViewModel.kt
  app/src/main/res/drawable-v24/img_clause_account.png
  app/src/main/res/drawable-v24/img_clause_service.png
  app/src/main/res/drawable/image_add_crop.xml
  app/src/main/res/layout/fragment_image_choose.xml
  app/src/main/res/layout/fragment_personal_info.xml
  app/src/main/res/layout/fragment_term.xml
Labels: feat, l2hyunwoo, pull request

#378 회원가입 오류 수정
  .idea/codeStyles/Project.xml
  app/release/output-metadata.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
  app/src/main/java/com/teambeme/beme/signup/viewmodel/SignUpViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_personal_info.xml
Labels: fix, l2hyunwoo, pull request

#396 Ub1n
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/detail/view/DetailActivity.kt
  app/src/main/java/com/teambeme/beme/detail/viewmodel/DetailViewModel.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/BottomProfileFragment.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_btn_scrap_unselected_detail.xml
  app/src/main/res/drawable/ic_scrap_on_detail.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_other_page.xml
  app/src/main/res/layout/item_bottom_write.xml
  app/src/main/res/layout/item_myscrap.xml
  app/src/main/res/layout/item_other_page.xml
  app/src/main/res/layout/reply_child.xml
  app/src/main/res/layout/reply_parent.xml
  app/src/main/res/values/colors.xml
Labels: feat, fix, style, ub1n

#404 워딩 수정/홈 정렬 문제 해결
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
  app/src/main/res/layout/fragment_permission_info.xml
  app/src/main/res/layout/item_home_question.xml
Labels: fix, l2hyunwoo, pull request

#407 #406 [FIX] : 회원가입 건너뛰기 에러 해결
  app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
Labels: fix, l2hyunwoo, pull request

#410 [DOCS] : README 수정
  README.md
Labels: docs, l2hyunwoo, pull request

#423 [FIX] : 회원가입/글쓰기 이슈 수정
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/following/viewmodel/FollowingViewModel.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
  app/src/main/java/com/teambeme/beme/signup/view/ImageChooseFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PermissionInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PersonalInfoFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/TermFragment.kt
  app/src/main/java/com/teambeme/beme/util/BindingAdapters.kt
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/navigation/sign_up_nav.xml
Labels: l2hyunwoo, pull request

#424 [DOCS] : 리드미 수정
  README.md
  document/ImageCropper.md
  document/IntentEmail.md
  document/Multipart.md
Labels: docs, l2hyunwoo, pull request

#433 Release/1.0.0
  app/build.gradle
  app/src/main/java/com/teambeme/beme/BeMeApplication.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
  app/src/main/java/com/teambeme/beme/notification/viewmodel/NoticeViewModel.kt
  app/src/main/java/com/teambeme/beme/signup/view/OnBoardFragment.kt
  app/src/main/java/com/teambeme/beme/signup/view/PermissionInfoFragment.kt
  app/src/main/res/layout/fragment_on_board.xml
  app/src/main/res/values/colors.xml
Labels: l2hyunwoo, pull request

#436 Yjooooo following
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/notification/viewmodel/NoticeViewModel.kt
  app/src/main/res/drawable/ic_scrap_off_detail.xml
  app/src/main/res/drawable/ic_scrap_on_detail.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_explore.xml
Labels: pull request, yjooooo

#437 Yjooooo following
  app/src/main/java/com/teambeme/beme/explore/viewmodel/ExploreViewModel.kt
  app/src/main/java/com/teambeme/beme/notification/viewmodel/NoticeViewModel.kt
  app/src/main/res/drawable/ic_scrap_off_detail.xml
  app/src/main/res/drawable/ic_scrap_on_detail.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_explore.xml
Labels: pull request, yjooooo

#439 #438 [FIX] Fix Bug in Following Fragment
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/res/layout/activity_following_show_all.xml
  app/src/main/res/layout/fragment_following.xml
Labels: pull request, yjooooo

#440 #438 [FIX] Fix Bug in Following Fragment
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/res/layout/activity_following_show_all.xml
  app/src/main/res/layout/fragment_following.xml
Labels: fix, yjooooo

#453 [Fix] Fix Bug in Explore, FollowingIdSearch, Following
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/explore/adapter/OtherQuestionsRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/adapter/FollowingProfilesRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/adapter/SearchProfilesRcvAdapter.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingShowAllActivity.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/adapter/IdSearchAdapter.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/view/FollowingAfterIdSearchActivity.kt
  app/src/main/java/com/teambeme/beme/idsearchfollowing/viewmodel/IdSearchViewModel.kt
  app/src/main/res/layout/item_explore_other_minds.xml
  app/src/main/res/layout/item_following_after_idsearch.xml
Labels: pull request, yjooooo

#461 Fix Bug when we use Dark Mode
  app/src/main/res/layout/activity_following_after_id_search.xml
  app/src/main/res/layout/activity_following_show_all.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_other_page.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: pull request, yjooooo

#463 #462 [FIX] 초기 상태바 컬러 검정으로 설정
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: pull request, yjooooo

#464 큰 오류는 수정해봄
  app/build.gradle
  app/src/main/java/com/teambeme/beme/answer/model/IntentAnswerData.kt
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/answer/viewmodel/AnswerViewModel.kt
  app/src/main/java/com/teambeme/beme/data/local/database/AppDatabase.kt
  app/src/main/java/com/teambeme/beme/data/local/entity/AnswerData.kt
  app/src/main/java/com/teambeme/beme/detail/viewmodel/DetailViewModel.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/activity_answer.xml
Labels: fix, l2hyunwoo, pull request

#472 AnswerActivity/Home 화면에서 발생하는 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/answer/view/AnswerActivity.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
  app/src/main/res/drawable/ic_splash.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/item_home_question.xml
Labels: fix, l2hyunwoo, pull request

#474 #468 [FEAT] : Splash 만들기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/splash/SplashActivity.kt
  app/src/main/java/com/teambeme/beme/util/KeyboardVisibilityUtils.kt
  app/src/main/res/drawable/splash.xml
  app/src/main/res/values/styles.xml
Labels: feat, l2hyunwoo, pull request

#475 #458 [FIX] : 특정 조건에 회원가입 버튼 활성화가 안되는 오류 해결
  app/src/main/java/com/teambeme/beme/signup/view/PersonalInfoFragment.kt
Labels: fix, l2hyunwoo

#477 Yjooooo
  app/src/main/java/com/teambeme/beme/login/view/LoginActivity.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/res/drawable/ic_hide_password.xml
  app/src/main/res/drawable/ic_show_password.xml
  app/src/main/res/layout/activity_answer.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_permission_info.xml
  app/src/main/res/layout/item_explore_other_questions.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
Labels: pull request, yjooooo

#479 #478 [Fix] Fix DarkMode Issue in SearchView
  app/src/main/res/drawable/ic_search_close.xml
  app/src/main/res/layout/activity_following_after_id_search.xml
  app/src/main/res/layout/activity_following_show_all.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_my_scrap.xml
  app/src/main/res/layout/fragment_my_write.xml
  app/src/main/res/values/styles.xml
Labels: pull request, yjooooo

#481 #480 [Fix] Fix DarkMode Issue in LoginView
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
Labels: pull request, yjooooo

#484 [FIX] : Answer 관련 오류 수정
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/res/layout/item_home_more_question.xml
Labels: fix, l2hyunwoo, pull request

#488 [FIX] : Base URL 수정 및 에러 수정
  app/release/output-metadata.json
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
Labels: l2hyunwoo, pull request

#489 Home 페이징 오류 수정/Explore 날짜 포매팅 오류 수정
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
Labels: fix, l2hyunwoo, pull request

#494 #493 [FIX] : Detail Page Reply Open/Close Bug Fix
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/detail/adapter/ReplyAdapter.kt
Labels: fix, pull request, ub1n

#495 Ub1n
  .idea/codeStyles/Project.xml
  app/src/main/java/com/teambeme/beme/detail/adapter/ReplyAdapter.kt
Labels: fix, pull request, ub1n

#498 Yjooooo
  app/release/output-metadata.json
  app/src/main/java/com/teambeme/beme/data/remote/singleton/RetrofitObjects.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreDetailActivity.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/java/com/teambeme/beme/home/adapter/QuestionPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/home/view/HomeFragment.kt
  app/src/main/java/com/teambeme/beme/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/teambeme/beme/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/teambeme/beme/mypage/adapter/MyPageViewPagerAdapter.kt
  app/src/main/java/com/teambeme/beme/mypage/view/MyPageFragment.kt
  app/src/main/res/layout/activity_explore_detail.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
Labels: pull request, yjooooo

#499 Yjooooo
  app/src/main/java/com/teambeme/beme/explore/view/ExploreDetailActivity.kt
  app/src/main/java/com/teambeme/beme/explore/view/ExploreFragment.kt
  app/src/main/java/com/teambeme/beme/following/view/FollowingFragment.kt
  app/src/main/res/layout/activity_explore_detail.xml
  app/src/main/res/layout/fragment_explore.xml
  app/src/main/res/layout/fragment_following.xml
Labels: pull request, yjooooo
